(function () {
  const EDITABLE = ["localhost", "127.0.0.1"].includes(location.hostname);
  const DATA_URL = "data/papers.json";

  const STR = {
    en: {
      searchPlaceholder: "Search title / keywords…",
      allYears: "All years",
      allVenues: "All venues",
      allStatus: "All",
      unread: "Unread",
      read: "Read",
      deep: "Deep read",
      topicAll: "All topics",
      topics: {
        summarization: "Summarization",
        multilingual: "Multilingual",
        "reinforcement learning": "RL",
      },
      statTotal: "Papers",
      statRead: "Brief read",
      statDeep: "Deep read",
      statStreak: "Day streak",
      heatmapCaption: (n, days) => `${n} papers read in the last ${days} days`,
      expand: "Show more",
      collapse: "Show less",
      generatedBy: (model, effort) => `Generated by ${model} · reasoning effort: ${effort}`,
      briefMark: "Mark brief",
      briefDone: "Brief read",
      deepMark: "Mark deep read",
      deepDone: "Deep read",
      readonlyBriefDone: "Brief read",
      readonlyBriefNo: "Unread",
      readonlyDeepDone: "Deep read",
      readonlyDeepNo: "Not deep read",
      prevPage: "Prev",
      nextPage: "Next",
      pageInfo: (p, total) => `Page ${p} of ${total}`,
      interestLabel: "Interest",
      readFull: "Read full text →",
    },
    zh: {
      searchPlaceholder: "搜索标题 / 关键词…",
      allYears: "全部年份",
      allVenues: "全部来源",
      allStatus: "全部",
      unread: "未读",
      read: "已读简报",
      deep: "已精读",
      topicAll: "全部主题",
      topics: {
        summarization: "摘要生成",
        multilingual: "多语言",
        "reinforcement learning": "强化学习",
      },
      statTotal: "论文总数",
      statRead: "读过简报",
      statDeep: "精读原文",
      statStreak: "连续阅读天数",
      heatmapCaption: (n, days) => `过去 ${days} 天内阅读了 ${n} 篇论文`,
      expand: "展开",
      collapse: "收起",
      generatedBy: (model, effort) => `由 ${model} 生成 · 推理强度：${effort}`,
      briefMark: "标记简报已读",
      briefDone: "简报已读",
      deepMark: "标记精读原文",
      deepDone: "已精读原文",
      readonlyBriefDone: "简报已读",
      readonlyBriefNo: "未读",
      readonlyDeepDone: "已精读原文",
      readonlyDeepNo: "未精读",
      prevPage: "上一页",
      nextPage: "下一页",
      pageInfo: (p, total) => `第 ${p} / ${total} 页`,
      interestLabel: "有意思指数",
      readFull: "阅读原文 →",
    },
  };

  function lang() {
    return document.documentElement.getAttribute("data-lang") === "zh" ? "zh" : "en";
  }

  let PAPERS = [];
  const activeTopics = new Set();
  const PAGE_SIZE = 10;
  let currentPage = 1;

  // Calendar keys are always in the reader's local timezone. read_at is stored in
  // UTC, so slicing the raw ISO string would put a late-evening read on the wrong
  // day for any timezone ahead of UTC.
  function localKey(d) {
    return (
      d.getFullYear() +
      "-" +
      String(d.getMonth() + 1).padStart(2, "0") +
      "-" +
      String(d.getDate()).padStart(2, "0")
    );
  }

  function dayKey(iso) {
    return localKey(new Date(iso));
  }

  async function load() {
    const res = await fetch(DATA_URL, { cache: "no-store" });
    PAPERS = await res.json();
    // Interest ratings live in a private, local-only file (gitignored). They are
    // merged in only on the local server; the public site never sees them.
    if (EDITABLE) {
      try {
        const interest = await (await fetch("data/interest.json", { cache: "no-store" })).json();
        PAPERS.forEach((p) => { if (interest[p.id] != null) p.interest = interest[p.id]; });
      } catch (e) { /* no local interest file yet */ }
    }
    initFilters();
    render();
  }

  function uniqueSorted(values) {
    return Array.from(new Set(values)).sort();
  }

  function initFilters() {
    const years = uniqueSorted(PAPERS.map((p) => p.year)).sort((a, b) => b - a);
    const venues = uniqueSorted(PAPERS.map((p) => p.venue));
    const allTopics = uniqueSorted(PAPERS.flatMap((p) => p.topics));

    const yearSel = document.getElementById("f-year");
    const venueSel = document.getElementById("f-venue");
    const readSel = document.getElementById("f-read");
    const topicsWrap = document.getElementById("f-topics");

    function fillSelect(sel, opts, allLabelKey) {
      sel.innerHTML = "";
      const allOpt = document.createElement("option");
      allOpt.value = "";
      allOpt.dataset.i18nKey = allLabelKey;
      sel.appendChild(allOpt);
      opts.forEach((v) => {
        const o = document.createElement("option");
        o.value = v;
        o.textContent = v;
        sel.appendChild(o);
      });
    }

    fillSelect(yearSel, years, "allYears");
    fillSelect(venueSel, venues, "allVenues");

    readSel.innerHTML = "";
    [["", "allStatus"], ["unread", "unread"], ["read", "read"], ["deep", "deep"]].forEach(([val, key]) => {
      const o = document.createElement("option");
      o.value = val;
      o.dataset.i18nKey = key;
      readSel.appendChild(o);
    });

    topicsWrap.innerHTML = "";
    topicsWrap.appendChild(makeChip("", STR[lang()].topicAll));
    allTopics.forEach((t) => topicsWrap.appendChild(makeChip(t, STR[lang()].topics[t] || t)));

    document.getElementById("f-search").addEventListener("input", onFilterChange);
    [yearSel, venueSel, readSel].forEach((el) => el.addEventListener("change", onFilterChange));

    applyI18nToControls();
  }

  function makeChip(topic, label) {
    const chip = document.createElement("button");
    chip.type = "button";
    chip.className = "topic-chip" + (activeTopics.size === 0 && topic === "" ? " active" : "");
    chip.textContent = label;
    chip.dataset.topic = topic;
    chip.addEventListener("click", () => {
      if (topic === "") {
        activeTopics.clear();
      } else if (activeTopics.has(topic)) {
        activeTopics.delete(topic);
      } else {
        activeTopics.add(topic);
      }
      onFilterChange();
    });
    return chip;
  }

  function onFilterChange() {
    currentPage = 1;
    render();
  }

  function applyI18nToControls() {
    const L = STR[lang()];
    document.getElementById("f-search").placeholder = L.searchPlaceholder;
    document
      .querySelectorAll("#f-year option[data-i18n-key], #f-venue option[data-i18n-key], #f-read option[data-i18n-key]")
      .forEach((o) => {
        o.textContent = L[o.dataset.i18nKey];
      });
    document.querySelectorAll("#f-topics .topic-chip").forEach((chip) => {
      const t = chip.dataset.topic;
      chip.textContent = t === "" ? L.topicAll : L.topics[t] || t;
      chip.classList.toggle("active", t === "" ? activeTopics.size === 0 : activeTopics.has(t));
    });
  }

  function filtered() {
    const q = document.getElementById("f-search").value.trim().toLowerCase();
    const year = document.getElementById("f-year").value;
    const venue = document.getElementById("f-venue").value;
    const readFilter = document.getElementById("f-read").value;

    return PAPERS.filter((p) => {
      if (year && String(p.year) !== year) return false;
      if (venue && p.venue !== venue) return false;
      if (readFilter === "read" && !p.read) return false;
      if (readFilter === "unread" && p.read) return false;
      if (readFilter === "deep" && !p.deep_read) return false;
      if (activeTopics.size > 0 && !p.topics.some((t) => activeTopics.has(t))) return false;
      if (q) {
        const hay = (p.title + " " + p.keywords.join(" ") + " " + p.venue).toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    }).sort((a, b) => (b.date_added + b.id).localeCompare(a.date_added + a.id));
  }

  function render() {
    applyI18nToControls();
    renderStats();
    renderHeatmap();
    renderList();
  }

  function renderStats() {
    const L = STR[lang()];
    const total = PAPERS.length;
    const read = PAPERS.filter((p) => p.read).length;
    const deep = PAPERS.filter((p) => p.deep_read).length;
    const wrap = document.getElementById("pr-stats");
    wrap.innerHTML = "";
    [
      [total, L.statTotal],
      [read, L.statRead],
      [deep, L.statDeep],
      [streak(), L.statStreak],
    ].forEach(([n, label]) => {
      const div = document.createElement("div");
      div.className = "pr-stat";
      div.innerHTML = `<div class="n">${n}</div><div class="l">${label}</div>`;
      wrap.appendChild(div);
    });
  }

  function streak() {
    const readDates = new Set(
      PAPERS.filter((p) => p.read && p.read_at).map((p) => dayKey(p.read_at))
    );
    let n = 0;
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const key = localKey(d);
      if (readDates.has(key)) {
        n++;
        d.setDate(d.getDate() - 1);
      } else {
        break;
      }
    }
    return n;
  }

  function renderHeatmap() {
    const L = STR[lang()];
    const counts = {};
    PAPERS.forEach((p) => {
      if (p.read && p.read_at) {
        const k = dayKey(p.read_at);
        counts[k] = (counts[k] || 0) + 1;
      }
    });

    const el = document.getElementById("heatmap");
    el.innerHTML = "";
    const WEEKS = 26;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    // Anchor the grid on the week containing today and walk back WEEKS-1 weeks, so
    // the final column is always the current week. (Subtracting WEEKS*7 days first
    // and *then* snapping to a week boundary shifted the whole grid into the past.)
    const start = new Date(today);
    start.setDate(start.getDate() - start.getDay());
    start.setDate(start.getDate() - (WEEKS - 1) * 7);

    let totalRecent = 0;
    const recentCutoff = new Date(today);
    recentCutoff.setDate(recentCutoff.getDate() - 89);

    for (let i = 0; i < WEEKS * 7; i++) {
      const d = new Date(start);
      d.setDate(start.getDate() + i);
      const key = localKey(d);
      const cell = document.createElement("div");
      cell.className = "cell";
      if (d > today) {
        cell.classList.add("future");
      } else {
        const c = counts[key] || 0;
        const level = c === 0 ? 0 : c === 1 ? 1 : c === 2 ? 2 : c <= 4 ? 3 : 4;
        cell.dataset.level = String(level);
        cell.title = `${key}: ${c}`;
        if (d >= recentCutoff) totalRecent += c;
      }
      el.appendChild(cell);
    }

    document.getElementById("heatmap-caption").textContent = L.heatmapCaption(totalRecent, 90);
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => (
      { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
    ));
  }

  function renderList() {
    const L = STR[lang()];
    const allItems = filtered();
    const totalPages = Math.max(1, Math.ceil(allItems.length / PAGE_SIZE));
    currentPage = Math.min(Math.max(currentPage, 1), totalPages);
    const start = (currentPage - 1) * PAGE_SIZE;
    const items = allItems.slice(start, start + PAGE_SIZE);

    const list = document.getElementById("pr-list");
    const empty = document.getElementById("pr-empty");
    list.innerHTML = "";
    empty.hidden = allItems.length > 0;

    items.forEach((p) => {
      const card = document.createElement("article");
      card.className = "pr-card";
      const topicLabels = p.topics.map((t) => L.topics[t] || t);

      card.innerHTML = `
        <div class="pr-card-head">
          <div>
            <div class="pr-card-title"><a href="${p.link}" target="_blank" rel="noopener">${escapeHtml(p.title)}</a></div>
            <div class="pr-card-meta">
              <span>${p.year}</span>
              <span class="pr-tag">${escapeHtml(p.venue)}</span>
              ${topicLabels.map((t) => `<span class="pr-tag">${escapeHtml(t)}</span>`).join("")}
              ${p.keywords.map((k) => `<span class="pr-tag">${escapeHtml(k)}</span>`).join("")}
            </div>
          </div>
        </div>
        <p class="pr-brief">${escapeHtml(p.brief)}</p>
        <button type="button" class="pr-brief-toggle">${L.expand}</button>
        <div class="pr-model-tag">${L.generatedBy(p.model, p.reasoning_effort)}</div>
      `;

      const actions = document.createElement("div");
      actions.className = "pr-actions";
      actions.appendChild(buildStatusWidget(p));
      if (EDITABLE) actions.appendChild(buildInterestWidget(p));
      const readFull = document.createElement("a");
      readFull.className = "pr-readfull";
      readFull.href = "reader.html?id=" + encodeURIComponent(p.id);
      readFull.textContent = L.readFull;
      actions.appendChild(readFull);
      card.querySelector(".pr-card-head").appendChild(actions);

      const briefEl = card.querySelector(".pr-brief");
      const briefToggle = card.querySelector(".pr-brief-toggle");
      briefToggle.addEventListener("click", () => {
        const expanded = briefEl.classList.toggle("expanded");
        briefToggle.textContent = expanded ? L.collapse : L.expand;
      });

      list.appendChild(card);
    });

    renderPagination(allItems.length, totalPages);
  }

  function renderPagination(totalItems, totalPages) {
    const L = STR[lang()];
    const wrap = document.getElementById("pr-pagination");
    wrap.innerHTML = "";
    if (totalItems === 0) return;

    const prev = document.createElement("button");
    prev.type = "button";
    prev.className = "pr-page-btn";
    prev.textContent = L.prevPage;
    prev.disabled = currentPage <= 1;
    prev.addEventListener("click", () => {
      currentPage--;
      renderList();
    });

    const info = document.createElement("span");
    info.className = "pr-page-info";
    info.textContent = L.pageInfo(currentPage, totalPages);

    const next = document.createElement("button");
    next.type = "button";
    next.className = "pr-page-btn";
    next.textContent = L.nextPage;
    next.disabled = currentPage >= totalPages;
    next.addEventListener("click", () => {
      currentPage++;
      renderList();
    });

    wrap.append(prev, info, next);
  }

  function buildStatusWidget(paper) {
    const wrap = document.createElement("div");
    wrap.className = "pr-status";

    const brief = document.createElement("button");
    brief.type = "button";
    brief.className = "pr-read-toggle brief" + (EDITABLE ? "" : " readonly");
    brief.innerHTML = `<span class="dot"></span><span class="label"></span>`;

    const deep = document.createElement("button");
    deep.type = "button";
    deep.className = "pr-read-toggle deep" + (EDITABLE ? "" : " readonly");
    deep.innerHTML = `<span class="ic">📖</span><span class="label"></span>`;

    function refresh() {
      const L = STR[lang()];
      brief.classList.toggle("is-read", !!paper.read);
      deep.classList.toggle("is-read", !!paper.deep_read);
      brief.querySelector(".label").textContent = paper.read
        ? (EDITABLE ? L.briefDone : L.readonlyBriefDone)
        : (EDITABLE ? L.briefMark : L.readonlyBriefNo);
      deep.querySelector(".label").textContent = paper.deep_read
        ? (EDITABLE ? L.deepDone : L.readonlyDeepDone)
        : (EDITABLE ? L.deepMark : L.readonlyDeepNo);
    }

    if (EDITABLE) {
      brief.addEventListener("click", () => {
        const next = !paper.read;
        updateStatus(paper, { read: next, deep_read: next ? paper.deep_read : false }, wrap, refresh);
      });
      deep.addEventListener("click", () => {
        const next = !paper.deep_read;
        updateStatus(paper, { read: next ? true : paper.read, deep_read: next }, wrap, refresh);
      });
      wrap.append(brief, deep);
    } else {
      brief.tabIndex = -1;
      deep.tabIndex = -1;
      if (paper.read) wrap.append(brief);
      if (paper.deep_read) wrap.append(deep);
    }

    refresh();
    return wrap;
  }

  async function updateStatus(paper, state, wrap, refresh) {
    const btns = Array.from(wrap.querySelectorAll(".pr-read-toggle"));
    btns.forEach((b) => (b.disabled = true));
    try {
      const res = await fetch("/api/read", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: paper.id, read: state.read, deep_read: state.deep_read }),
      });
      if (!res.ok) throw new Error("request failed");
      const updated = await res.json();
      paper.read = updated.read;
      paper.read_at = updated.read_at;
      paper.deep_read = updated.deep_read;
      paper.deep_read_at = updated.deep_read_at;
      refresh();
      renderStats();
      renderHeatmap();
    } catch (e) {
      console.error(e);
    } finally {
      btns.forEach((b) => (b.disabled = false));
    }
  }

  function buildInterestWidget(paper) {
    const L = STR[lang()];
    const wrap = document.createElement("div");
    wrap.className = "pr-interest" + (EDITABLE ? "" : " readonly");
    wrap.title = L.interestLabel;

    for (let i = 1; i <= 5; i++) {
      const star = document.createElement("button");
      star.type = "button";
      star.className = "pr-star" + (paper.interest && i <= paper.interest ? " filled" : "");
      star.textContent = "★";
      star.dataset.value = String(i);
      if (EDITABLE) {
        star.addEventListener("click", () => {
          const next = paper.interest === i ? null : i;
          setInterest(paper, next, wrap);
        });
      } else {
        star.tabIndex = -1;
      }
      wrap.appendChild(star);
    }
    return wrap;
  }

  async function setInterest(paper, value, wrap) {
    const stars = Array.from(wrap.querySelectorAll(".pr-star"));
    stars.forEach((s) => (s.disabled = true));
    try {
      const res = await fetch("/api/interest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: paper.id, interest: value }),
      });
      if (!res.ok) throw new Error("request failed");
      const updated = await res.json();
      paper.interest = updated.interest;
      stars.forEach((s) => {
        s.classList.toggle("filled", paper.interest && Number(s.dataset.value) <= paper.interest);
      });
    } catch (e) {
      console.error(e);
    } finally {
      stars.forEach((s) => (s.disabled = false));
    }
  }

  document.getElementById("lang-toggle").addEventListener("click", () => {
    setTimeout(render, 0);
  });

  load();
})();
