(function () {
  const EDITABLE = ["localhost", "127.0.0.1"].includes(location.hostname);
  const DATA_URL = "data/papers.json";

  const STR = {
    en: {
      searchPlaceholder: "Search title / keywords…",
      allYears: "All years",
      allVenues: "All venues",
      allStatus: "All",
      unread: "Unread",
      read: "Read",
      topicAll: "All topics",
      topics: {
        summarization: "Summarization",
        multilingual: "Multilingual",
        "reinforcement learning": "RL",
      },
      statTotal: "Papers",
      statRead: "Read",
      statUnread: "Unread",
      statStreak: "Day streak",
      heatmapCaption: (n, days) => `${n} papers read in the last ${days} days`,
      expand: "Show more",
      collapse: "Show less",
      generatedBy: (model, effort) => `Generated by ${model} · reasoning effort: ${effort}`,
      markRead: "Mark read",
      markUnread: "Read",
      readonlyRead: "Read",
      readonlyUnread: "Unread",
    },
    zh: {
      searchPlaceholder: "搜索标题 / 关键词…",
      allYears: "全部年份",
      allVenues: "全部来源",
      allStatus: "全部",
      unread: "未读",
      read: "已读",
      topicAll: "全部主题",
      topics: {
        summarization: "摘要生成",
        multilingual: "多语言",
        "reinforcement learning": "强化学习",
      },
      statTotal: "论文总数",
      statRead: "已读",
      statUnread: "未读",
      statStreak: "连续阅读天数",
      heatmapCaption: (n, days) => `过去 ${days} 天内阅读了 ${n} 篇论文`,
      expand: "展开",
      collapse: "收起",
      generatedBy: (model, effort) => `由 ${model} 生成 · 推理强度：${effort}`,
      markRead: "标记已读",
      markUnread: "已读",
      readonlyRead: "已读",
      readonlyUnread: "未读",
    },
  };

  function lang() {
    return document.documentElement.getAttribute("data-lang") === "zh" ? "zh" : "en";
  }

  let PAPERS = [];
  const activeTopics = new Set();

  function dayKey(iso) {
    return iso.slice(0, 10);
  }

  async function load() {
    const res = await fetch(DATA_URL, { cache: "no-store" });
    PAPERS = await res.json();
    initFilters();
    render();
  }

  function uniqueSorted(values) {
    return Array.from(new Set(values)).sort();
  }

  function initFilters() {
    const years = uniqueSorted(PAPERS.map((p) => p.year)).sort((a, b) => b - a);
    const venues = uniqueSorted(PAPERS.map((p) => p.venue));
    const allTopics = uniqueSorted(PAPERS.flatMap((p) => p.topics));

    const yearSel = document.getElementById("f-year");
    const venueSel = document.getElementById("f-venue");
    const readSel = document.getElementById("f-read");
    const topicsWrap = document.getElementById("f-topics");

    function fillSelect(sel, opts, allLabelKey) {
      sel.innerHTML = "";
      const allOpt = document.createElement("option");
      allOpt.value = "";
      allOpt.dataset.i18nKey = allLabelKey;
      sel.appendChild(allOpt);
      opts.forEach((v) => {
        const o = document.createElement("option");
        o.value = v;
        o.textContent = v;
        sel.appendChild(o);
      });
    }

    fillSelect(yearSel, years, "allYears");
    fillSelect(venueSel, venues, "allVenues");

    readSel.innerHTML = "";
    [["", "allStatus"], ["unread", "unread"], ["read", "read"]].forEach(([val, key]) => {
      const o = document.createElement("option");
      o.value = val;
      o.dataset.i18nKey = key;
      readSel.appendChild(o);
    });

    topicsWrap.innerHTML = "";
    topicsWrap.appendChild(makeChip("", STR[lang()].topicAll));
    allTopics.forEach((t) => topicsWrap.appendChild(makeChip(t, STR[lang()].topics[t] || t)));

    document.getElementById("f-search").addEventListener("input", render);
    [yearSel, venueSel, readSel].forEach((el) => el.addEventListener("change", render));

    applyI18nToControls();
  }

  function makeChip(topic, label) {
    const chip = document.createElement("button");
    chip.type = "button";
    chip.className = "topic-chip" + (activeTopics.size === 0 && topic === "" ? " active" : "");
    chip.textContent = label;
    chip.dataset.topic = topic;
    chip.addEventListener("click", () => {
      if (topic === "") {
        activeTopics.clear();
      } else if (activeTopics.has(topic)) {
        activeTopics.delete(topic);
      } else {
        activeTopics.add(topic);
      }
      render();
    });
    return chip;
  }

  function applyI18nToControls() {
    const L = STR[lang()];
    document.getElementById("f-search").placeholder = L.searchPlaceholder;
    document
      .querySelectorAll("#f-year option[data-i18n-key], #f-venue option[data-i18n-key], #f-read option[data-i18n-key]")
      .forEach((o) => {
        o.textContent = L[o.dataset.i18nKey];
      });
    document.querySelectorAll("#f-topics .topic-chip").forEach((chip) => {
      const t = chip.dataset.topic;
      chip.textContent = t === "" ? L.topicAll : L.topics[t] || t;
      chip.classList.toggle("active", t === "" ? activeTopics.size === 0 : activeTopics.has(t));
    });
  }

  function filtered() {
    const q = document.getElementById("f-search").value.trim().toLowerCase();
    const year = document.getElementById("f-year").value;
    const venue = document.getElementById("f-venue").value;
    const readFilter = document.getElementById("f-read").value;

    return PAPERS.filter((p) => {
      if (year && String(p.year) !== year) return false;
      if (venue && p.venue !== venue) return false;
      if (readFilter === "read" && !p.read) return false;
      if (readFilter === "unread" && p.read) return false;
      if (activeTopics.size > 0 && !p.topics.some((t) => activeTopics.has(t))) return false;
      if (q) {
        const hay = (p.title + " " + p.keywords.join(" ") + " " + p.venue).toLowerCase();
        if (!hay.includes(q)) return false;
      }
      return true;
    }).sort((a, b) => (b.date_added + b.id).localeCompare(a.date_added + a.id));
  }

  function render() {
    applyI18nToControls();
    renderStats();
    renderHeatmap();
    renderList();
  }

  function renderStats() {
    const L = STR[lang()];
    const total = PAPERS.length;
    const read = PAPERS.filter((p) => p.read).length;
    const wrap = document.getElementById("pr-stats");
    wrap.innerHTML = "";
    [
      [total, L.statTotal],
      [read, L.statRead],
      [total - read, L.statUnread],
      [streak(), L.statStreak],
    ].forEach(([n, label]) => {
      const div = document.createElement("div");
      div.className = "pr-stat";
      div.innerHTML = `<div class="n">${n}</div><div class="l">${label}</div>`;
      wrap.appendChild(div);
    });
  }

  function streak() {
    const readDates = new Set(
      PAPERS.filter((p) => p.read && p.read_at).map((p) => dayKey(p.read_at))
    );
    let n = 0;
    const d = new Date();
    // eslint-disable-next-line no-constant-condition
    while (true) {
      const key = d.toISOString().slice(0, 10);
      if (readDates.has(key)) {
        n++;
        d.setDate(d.getDate() - 1);
      } else {
        break;
      }
    }
    return n;
  }

  function renderHeatmap() {
    const L = STR[lang()];
    const counts = {};
    PAPERS.forEach((p) => {
      if (p.read && p.read_at) {
        const k = dayKey(p.read_at);
        counts[k] = (counts[k] || 0) + 1;
      }
    });

    const el = document.getElementById("heatmap");
    el.innerHTML = "";
    const WEEKS = 26;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const start = new Date(today);
    start.setDate(start.getDate() - (WEEKS * 7 - 1));
    start.setDate(start.getDate() - start.getDay());

    let totalRecent = 0;
    const recentCutoff = new Date(today);
    recentCutoff.setDate(recentCutoff.getDate() - 89);

    for (let i = 0; i < WEEKS * 7; i++) {
      const d = new Date(start);
      d.setDate(start.getDate() + i);
      const key = d.toISOString().slice(0, 10);
      const cell = document.createElement("div");
      cell.className = "cell";
      if (d > today) {
        cell.classList.add("future");
      } else {
        const c = counts[key] || 0;
        const level = c === 0 ? 0 : c === 1 ? 1 : c === 2 ? 2 : c <= 4 ? 3 : 4;
        cell.dataset.level = String(level);
        cell.title = `${key}: ${c}`;
        if (d >= recentCutoff) totalRecent += c;
      }
      el.appendChild(cell);
    }

    document.getElementById("heatmap-caption").textContent = L.heatmapCaption(totalRecent, 90);
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, (c) => (
      { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
    ));
  }

  function renderList() {
    const L = STR[lang()];
    const items = filtered();
    const list = document.getElementById("pr-list");
    const empty = document.getElementById("pr-empty");
    list.innerHTML = "";
    empty.hidden = items.length > 0;

    items.forEach((p) => {
      const card = document.createElement("article");
      card.className = "pr-card";
      const topicLabels = p.topics.map((t) => L.topics[t] || t);

      card.innerHTML = `
        <div class="pr-card-head">
          <div>
            <div class="pr-card-title"><a href="${p.link}" target="_blank" rel="noopener">${escapeHtml(p.title)}</a></div>
            <div class="pr-card-meta">
              <span>${p.year}</span>
              <span class="pr-tag">${escapeHtml(p.venue)}</span>
              ${topicLabels.map((t) => `<span class="pr-tag">${escapeHtml(t)}</span>`).join("")}
              ${p.keywords.map((k) => `<span class="pr-tag">${escapeHtml(k)}</span>`).join("")}
            </div>
          </div>
        </div>
        <p class="pr-brief">${escapeHtml(p.brief)}</p>
        <button type="button" class="pr-brief-toggle">${L.expand}</button>
        <div class="pr-model-tag">${L.generatedBy(p.model, p.reasoning_effort)}</div>
      `;

      const toggle = document.createElement("button");
      toggle.type = "button";
      toggle.className = "pr-read-toggle" + (p.read ? " is-read" : "") + (EDITABLE ? "" : " readonly");
      toggle.innerHTML = `<span class="dot"></span><span class="label"></span>`;
      const labelEl = toggle.querySelector(".label");
      labelEl.textContent = p.read
        ? (EDITABLE ? L.markUnread : L.readonlyRead)
        : (EDITABLE ? L.markRead : L.readonlyUnread);
      if (EDITABLE) {
        toggle.addEventListener("click", () => toggleRead(p, toggle, labelEl));
      } else {
        toggle.tabIndex = -1;
      }
      card.querySelector(".pr-card-head").appendChild(toggle);

      const briefEl = card.querySelector(".pr-brief");
      const briefToggle = card.querySelector(".pr-brief-toggle");
      briefToggle.addEventListener("click", () => {
        const expanded = briefEl.classList.toggle("expanded");
        briefToggle.textContent = expanded ? L.collapse : L.expand;
      });

      list.appendChild(card);
    });
  }

  async function toggleRead(paper, toggleEl, labelEl) {
    const next = !paper.read;
    toggleEl.disabled = true;
    try {
      const res = await fetch("/api/read", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: paper.id, read: next }),
      });
      if (!res.ok) throw new Error("request failed");
      const updated = await res.json();
      paper.read = updated.read;
      paper.read_at = updated.read_at;
      renderStats();
      renderHeatmap();
      toggleEl.classList.toggle("is-read", paper.read);
      const L = STR[lang()];
      labelEl.textContent = paper.read ? L.markUnread : L.markRead;
    } catch (e) {
      console.error(e);
    } finally {
      toggleEl.disabled = false;
    }
  }

  document.getElementById("lang-toggle").addEventListener("click", () => {
    setTimeout(render, 0);
  });

  load();
})();
